<?php

namespace NotificationBundle\Repository;

/**
 * campanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campanyRepository extends \Doctrine\ORM\EntityRepository
{
}
